# Generated by Django 4.0.4 on 2022-05-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, default=0, null=True)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('id_pedido', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=40)),
                ('valor', models.FloatField()),
                ('medida', models.CharField(choices=[('gm', 'grama'), ('kg', 'quilo'), ('l', 'litro'), ('u', 'unidade'), ('dz', 'dúzia')], max_length=2)),
                ('organico', models.BooleanField(blank=True, default=False, null=True)),
                ('descricao', models.TextField(max_length=500)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
